# Generated by Django 3.0.7 on 2020-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='labo_affiliation',
            field=models.CharField(blank=True, choices=[('1', 'Category A '), ('2', 'Category B '), ('3', 'Category C '), ('4', 'Category D ')], max_length=100),
        ),
    ]
