# Generated by Django 3.0.8 on 2020-07-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('resumé', models.CharField(blank=True, max_length=500)),
                ('dateEdition', models.DateField(blank=True)),
                ('maison_ed', models.CharField(blank=True, max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('typeArticl', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('path', models.FileField(blank=True, null=True, upload_to='chapter/%Y/%m/%D/')),
            ],
        ),
    ]
