# Generated by Django 3.0.8 on 2020-07-15 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlPub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('resumé', models.CharField(blank=True, max_length=500)),
                ('dateEdition', models.DateField(blank=True)),
                ('maison_ed', models.CharField(blank=True, max_length=500)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('typeArticl', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('path', models.FileField(blank=True, null=True, upload_to='chapter/%Y/%m/%D/')),
                ('auteurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Articl',
        ),
    ]
