# Generated by Django 3.0.8 on 2020-07-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('articl', '0003_auto_20200716_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlpub',
            name='auteurEcrit',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='articlpub',
            name='typeArticl',
            field=models.CharField(choices=[('1', 'Research Article'), ('2', 'Research Paper'), ('3', 'Review Paper'), ('4', 'Review Article'), ('5', 'Peer-Reviewed Articles')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Ecrit',
        ),
    ]
