# Generated by Django 3.0.7 on 2020-08-07 01:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0006_auto_20200729_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlpub',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articlpub',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
