# Generated by Django 3.0.7 on 2020-08-07 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articl', '0007_auto_20200807_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlpub',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='articlpub',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='chapter/%Y/'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('articl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articl.ArticlPub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
