# Generated by Django 3.0.7 on 2020-08-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
