# Generated by Django 3.0.7 on 2020-09-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0011_articlpub_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlpub',
            name='domaineArt',
            field=models.CharField(choices=[('1', 'Computer Hardware'), ('2', 'Computer Networking'), ('3', 'Computer Software'), ('4', 'Cloud computing'), ('5', 'Cyber Security and Ethical Hacking'), ('6', 'Data Science and Data Analysis'), ('7', 'Programming Language'), ('8', 'Artificial intelligence'), ('9', 'Operating system'), ('10', 'Web Development'), ('11', 'Web Designing'), ('12', 'Graphics design'), ('13', 'Network Analytics and testing'), ('14', 'Robotics'), ('15', 'others field')], default='Computer Software ', max_length=100),
        ),
    ]
