# Generated by Django 3.0.7 on 2020-09-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0012_articlpub_domaineart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlpub',
            name='resumé',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
